@baseUrl = http://localhost:3000

### get hello
GET {{baseUrl}}/tasks/hello

### test
POST {{baseUrl}}/auth/test

### get all task
# GET {{baseUrl}}/tasks
GET {{baseUrl}}/tasks?status=OPEN
# GET {{baseUrl}}/tasks?search=nest
# GET {{baseUrl}}/tasks?status=IN_PROGRESS&limit=10&page=2

### create task
POST {{baseUrl}}/tasks
Content-Type: application/json

{
//  "title": "learn nest js",
//  "title": "learn backend development",
//  "title": "learn frontend development",
  "title": "learn full stack development 2",
  "description": "this is the first task"
}

### Get task by id
GET {{baseUrl}}/tasks/96e78492-fb75-4382-831c-7dc8dd790fc5

### Update task by id
PATCH {{baseUrl}}/tasks/66defb0a-694c-4067-8e0a-f21db106ce31
Content-Type: application/json

{
  "status": "IN_PROGRESS"
}

### Delete task by id
DELETE {{baseUrl}}/tasks/66defb0a-694c-4067-8e0a-f21db106ce31



############################################################################################
####################################  SAMPLE  ##############################################
############################################################################################
# @name login
POST {{baseUrl}}/api/login HTTP/1.1
Content-Type: application/x-www-form-urlencoded

name=foo&password=bar

###

@authToken = {{login.response.headers.X-AuthToken}}

# @name createComment
POST {{baseUrl}}/comments HTTP/1.1
Authorization: {{authToken}}
Content-Type: application/json

{
    "content": "fake content"
}

###

@commentId = {{createComment.response.body.$.id}}

# @name getCreatedComment
GET {{baseUrl}}/comments/{{commentId}} HTTP/1.1
Authorization: {{authToken}}

###

# @name getReplies
GET {{baseUrl}}/comments/{{commentId}}/replies HTTP/1.1
Accept: application/xml

###

# @name getFirstReply
GET {{baseUrl}}/comments/{{commentId}}/replies/{{getReplies.response.body.//reply[1]/@id}}

